project:
  type: website

website:
  title: Matthew Burns
  description: A website and portfolio for data science projects and insights
  navbar:
    background: "#343A40"
    title: matthew burns
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light:
        - sandstone
        - brand
      dark:
        - darkly
        - brand
    css: styles.css
    toc: true



