project:
  type: website

website:
  title: Matthew Burns
  description: A website and portfolio for data science projects and insights
  site-url: https://msburns.netlify.app/

  search: 
    location: navbar
    type: overlay

  navbar:
    background: "#343A40"
    title: matthew burns

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: /posts/
        text: Posts
      - href: /projects/
        text: Projects
        
    right:
      - icon: github
        href: https://github.com/msburns24/website/

format:
  html:
    link-external-icon: true
    respect-user-color-scheme: true
    theme:
      light:
        - sandstone
        - theme-light.scss
      dark:
        - sandstone
        - theme-dark.scss
    css: styles.css
    toc: true
